[project]
name = "rds-pg"
version = "0.6.0"
description = "PostgreSQL RDS CloudFormation template with SQL notebook"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.4.3",
    "jupysql>=0.10.17",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
    "toml>=0.10.2",
    "jupyterlab-sql-explorer>=0.2.1",
]
